name: Coverage

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
      - name: Installing Node
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: npm
      - name: Installing dependencies
        run: npm ci
        env:
          PUPPETEER_SKIP_DOWNLOAD: true
      - name: Installing gulp command line interface
        run: npm install gulp-cli
      - name: Install Chrome
        id: setup-chrome
        uses: browser-actions/setup-chrome@v1
      - name: Run tests with coverage
        run: npm run coverage:lcov
        env:
          PUPPETEER_EXECUTABLE_PATH: ${{ steps.setup-chrome.outputs.chrome-path }}
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: ./coverage/lcov.info
          token: ${{ secrets.CODECOV_TOKEN }} # required
