name: Testing

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [22.x, 24.x, 26.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Installing Node ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - name: Installing dependencies
        run: npm ci
        env:
          PUPPETEER_SKIP_DOWNLOAD: true
      - name: Installing gulp command line interface
        run: npm install gulp-cli
      - name: Install Chrome
        id: setup-chrome
        uses: browser-actions/setup-chrome@v1
      - name: Run tests
        run: npm test -- --no-sandbox --disable-setuid-sandbox
        env:
          PUPPETEER_EXECUTABLE_PATH: ${{ steps.setup-chrome.outputs.chrome-path }}
